# Generated by Django 5.0.2 on 2024-02-26 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('plan_file', models.FileField(blank=True, null=True, upload_to='site_visit_plans/')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed')], max_length=50, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitevisitAPP.sitevisit')),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisitPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='site_visit_photos/')),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitevisitAPP.sitevisit')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag1', models.CharField(blank=True, max_length=255, null=True)),
                ('tag2', models.CharField(blank=True, max_length=255, null=True)),
                ('tag3', models.CharField(blank=True, max_length=255, null=True)),
                ('tag4', models.CharField(blank=True, max_length=255, null=True)),
                ('tag5', models.CharField(blank=True, max_length=255, null=True)),
                ('tag6', models.CharField(blank=True, max_length=255, null=True)),
                ('tag7', models.CharField(blank=True, max_length=255, null=True)),
                ('tag8', models.CharField(blank=True, max_length=255, null=True)),
                ('tag9', models.CharField(blank=True, max_length=255, null=True)),
                ('tag10', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitevisitAPP.sitevisitphoto')),
            ],
        ),
    ]
