# Generated by Django 5.0.2 on 2024-02-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisitphoto',
            name='tag',
        ),
    ]
