# Generated by Django 5.0.2 on 2024-02-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitAPP', '0002_remove_sitevisitphoto_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phototag',
            name='tag10',
        ),
        migrations.RemoveField(
            model_name='phototag',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='phototag',
            name='tag3',
        ),
        migrations.RemoveField(
            model_name='phototag',
            name='tag4',
        ),
        migrations.RemoveField(
            model_name='phototag',
            name='tag5',
        ),
        migrations.RemoveField(
            model_name='phototag',
            name='tag6',
        ),
        migrations.RemoveField(
            model_name='phototag',
            name='tag7',
        ),
        migrations.RemoveField(
            model_name='phototag',
            name='tag8',
        ),
        migrations.RemoveField(
            model_name='phototag',
            name='tag9',
        ),
        migrations.AlterField(
            model_name='phototag',
            name='tag1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
