# Generated by Django 5.0.2 on 2024-02-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitAPP', '0003_remove_phototag_tag10_remove_phototag_tag2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phototag',
            old_name='tag1',
            new_name='tag',
        ),
    ]
