# Generated by Django 5.0.2 on 2024-02-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitAPP', '0004_rename_tag1_phototag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitphoto',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PhotoTag',
        ),
    ]
