# Generated by Django 5.0.2 on 2024-03-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitAPP', '0005_sitevisitphoto_tags_delete_phototag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisitphoto',
            name='image',
            field=models.FileField(upload_to='site_visit_photos/'),
        ),
    ]
