# Generated by Django 5.0.2 on 2024-03-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitAPP', '0010_phototags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitphoto',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PhotoTags',
        ),
    ]
