# Generated by Django 5.0.2 on 2024-03-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitAPP', '0015_sitevisitphoto_tag_delete_imagetag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitevisitphoto',
            old_name='image',
            new_name='images',
        ),
    ]
