# Generated by Django 5.0.2 on 2024-03-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitAPP', '0017_alter_sitevisitphoto_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisitphoto',
            name='images',
            field=models.FileField(blank=True, default='', null=True, upload_to='site_visit_photos/'),
        ),
    ]
