# Generated by Django 5.0.2 on 2024-03-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitAPP', '0027_remove_sitevisit_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_mob_num', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('country_code', models.IntegerField()),
            ],
        ),
    ]
