# Generated by Django 5.0.2 on 2024-03-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitAPP', '0028_clientdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='country_code',
            field=models.CharField(),
        ),
    ]
