# Generated by Django 5.0.2 on 2024-03-27 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitAPP', '0029_alter_clientdetails_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='category',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Industry', 'Industry')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
