# Generated by Django 5.0.2 on 2024-03-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitAPP', '0030_clientdetails_category_clientdetails_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetails',
            old_name='place',
            new_name='location',
        ),
    ]
