# Generated by Django 5.0.2 on 2024-03-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitAPP', '0031_rename_place_clientdetails_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='category',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Industry', 'Industry'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
